name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build Release with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --scan -s
    - name: Push release to release_library branch
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        mkdir temp
        cd temp
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git clone -b release_library --single-branch https://github.com/koalaopensource/koala.git .
        cp ../koala/build/outputs/aar/koala-release.aar koala-release.aar
        if git commit -a -m "Library release for $git_hash";then
          git remote set-url origin "https://koalaopensource:${{ secrets.GITHUB_TOKEN }}@github.com/koalaopensource/koala.git"
          git push origin release_library
        else
          echo 'No updates to library'
        fi
